### PR TITLE
Feature/8 run everything through webpack

### PR DESCRIPTION
**Pull request by EdgarOPG**
* The remote dependencies was added to the project via npm.
* Now all dependencies are loaded through webpack.
* Import syntax changed from CommonJs (module.exports, require) to ES6 syntax (export class, import from)

### CODE REVIEW

**Comment by rrgarciach** [comment]
@EdgarOPG I got confused... I Thought this was the one for Issue No. 9. It's pretty much exactly the same. Why?

**Comment by EdgarOPG** [comment]
That's because I created branch 8 from branch 9, and the reason was that I started with css refactoring, but had to implements some webpack features first in the wake of finish that task.

**Comment by BentleyDavis** [comment]
When I run `webpack` I get:

```
ERROR in ./index.js
Module not found: Error: Can't resolve 'style-loader' in 'C:\Users\Bentley\Documents\GitHub\ReasonRoot'
 @ ./index.js 7:0-28

ERROR in ./js/src/rrDisplay.js
Module not found: Error: Can't resolve 'hyperhtml' in 'C:\Users\Bentley\Documents\GitHub\ReasonRoot\js\src'
 @ ./js/src/rrDisplay.js 1:0-34
 @ ./index.js
```

Am I doing something wrong?

**Comment by BentleyDavis** [comment]
These should really be a pull request to the `dev` branch. Mast is automatically deployed so it is after it has been tested.

**Comment by BentleyDavis** [comment]
The code looks great! 
I look forward to your pull requests on `dev`. Thanks.

**Comment by rrgarciach** [comment]
Reopening and switching to point to `dev` branch

**Pull request merged**
